services:
  inference:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: hbr_inference
    environment:
      DATA_DIR: /app/data/raw
      LOG_DIR: /app/data/logs
      PYTHONUNBUFFERED: "1"
    working_dir: /app
    volumes:
      - ./:/app
      - ./data/subset:/app/data/subset:ro
      - ./data/logs:/app/data/logs


    command: [ "sh", "-lc", "python -m src.main && tail -f /dev/null" ]
    stdin_open: true
    tty: true