experiment_name: "baseline_finetune"
directories:
  manifests: "data/manifests"
  raw: "data/raw"
  checkpoints: "logs/checkpoints"
  logs: "logs/metrics"

training:
  epochs: 10
  batch_size: 4 # set to 4 bcs it can choke RAM or VRAM
  learning_rate: 0.001
  num_classes: 5